services:
  db:
    image: postgres:15
    container_name: notif-test-postgres
    environment:
      POSTGRES_DB: notif_test
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
